spring.application.name=gestion-budget

spring.datasource.url=jdbc:postgresql://localhost:5433/gestion_budget
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver